- package.json
sets the right repository so dependabot automerges looks in the right place via github API 
@W-8776229@
> chore: wrong repo

- .circleci/config.yml
- package.json
- src/lib/installationVerification.ts
- src/lib/npmCommand.ts
- test/lib/installationVerification.test.ts
- test/lib/npmCommand.test.ts
- test/nuts/plugin-install.nut.ts
- yarn.lock
Replaces http commands in favor of npm commands
@W-9642544@
> fix: use npm instead of http

- package.json
Allows using plugin-trust as a standalone binary `sf-trust`.
@W-9496922@
> fix: install plugin-trust as an executable

- src/lib/installationVerification.ts
Include the provided tag when getting npm meta from `npm show`
@W-9911065@
> fix: use tag when getting npm meta

- .circleci/config.yml
- package.json
- src/commands/plugins/trust/verify.ts
- src/hooks/verifyInstallSignature.ts
- src/lib/installationVerification.ts
- src/lib/npmCommand.ts
- test/lib/installationVerification.test.ts
- test/lib/npmCommand.test.ts
- test/nuts/plugin-install.nut.ts
- yarn.lock
@W-9930707@
https://github.com/forcedotcom/cli/issues/1198
> fix: verify fails if node not installed

- src/lib/installationVerification.ts
- src/lib/npmCommand.ts
- test/lib/npmCommand.test.ts
Fix empty error reports when an npm command (`show`, `pack`) fails. 
`npm show` doesn't find a specific package version
```
Checking for digital signature.
ERROR running plugins:trust:verify:  Failed to find @salesforce/plugin-source@1.2.5 in the registry
```
Possible race condition scenario:
1. `npm show` finds @salesforce/plugin-source@1.2.5, then
2. `npm pack` fails to find it:
```
ERROR running plugins:trust:verify:  Failed to fetch tarball from the registry:
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @salesforce/plugin-source@1.2.5.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! A complete log of this run can be found in:
npm ERR! …
```
> fix: improve error messages when shelling out npm commands

- src/lib/installationVerification.ts
- src/lib/npmCommand.ts
- test/lib/installationVerification.test.ts
- test/lib/npmCommand.test.ts
Adds polling logic to `NpmModule`, add new method `fetchTarball` that polls `npm pack` until the tarball is available.
**Note**:
[plugin-rel-mgmt already polls `npm view` in the release process ](https://github.com/salesforcecli/plugin-release-management/blob/251fdf34eef5e1d758dd92f4e32e780b5989a03c/src/repository.ts#L154),`npm pack` is the one failing right after `npm view` successfully retrieves the metadata.
Circle logs (signature verification step failed):
[plugin-source](https://app.circleci.com/pipelines/github/salesforcecli/plugin-source/1374/workflows/045c3207-5c40-436c-b25d-5204a8940cdb/jobs/4406/parallel-runs/0/steps/0-118)
[toolbelt](https://app.circleci.com/pipelines/github/salesforcecli/toolbelt/729/workflows/fa389933-53ea-46a1-a98d-1e1a1c9a8344/jobs/3953/parallel-runs/0/steps …
> fix: poll `npm pack` until tarball is available

- src/shared/installationVerification.ts
simplify got/stream stuff
Readable.from() https://nodejs.org/api/stream.html#streamreadablefromiterable-options
> refactor: more idiomatic got/Readable

- .github/workflows/onPushToMain.yml
- .github/workflows/onRelease.yml
- package.json
- src/hooks/verifyInstallSignature.ts
- test/hooks/verifyInstallSignatureHook.test.ts
> this is on prerelease.  be sure to remove the `qa` tag before merging.
background https://salesforce-internal.slack.com/archives/G02K6C90RBJ/p1682563856812799
skips the signature check if the plugin being installed is in the CLI's JIT list
because the sig verification stuff writes to stdout
which breaks json output when `sf some:jit --json` prints messages from the verification. 
QA: 
just-nuts from [here](https://github.com/salesforcecli/cli/actions/runs/4820315494) should work better with (ex) [plugin-signups](https://github.com/salesforcecli/cli/actions/runs/4820315494/jobs/8586009528) that were previously failing like [this](https://github.com/salesforcecli/cli/actions/runs/4813536200/jobs/8574084844)
you can run something jit with json (ex: `sf org list shape --json > result.json`) …
> fix: jit with json

- package.json
- src/hooks/jitPluginInstall.ts
- yarn.lock
hardcode GDPR replacement string to avoid a large import of a non-exported class
https://github.com/salesforcecli/cli/actions/runs/5868899251/job/15913774669
> refactor: don't import all of telemetry just for a string

- .github/dependabot.yml
- .github/workflows/failureNotifications.yml
- .github/workflows/update-npm-version.yml
We have a customer needs the included `npm` version to be one that has (at some point) been bundled with node lts.
We will install the `npm` version that is included with the Github Action runner's LTS node
If there are changes, we will commit them to `main`. This will run weekly on Tuesdays, that way it will be included in Tuesday's `nightly` to be promoted to `latest-rc` on Wednesday
[@W-13848117@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-13848117)
Issue: https://github.com/forcedotcom/cli/issues/2327
Related: https://github.com/oclif/plugin-plugins/pull/647
> Add npm update workflow

- README.md
- src/shared/installationVerification.ts
If the signature or cert cannot be found, you can now continue to install the plugin by using the allowList
QA
- Pull and link `plugin-trust`
- Create a file at `$HOME/.config/sf/unsignedPluginAllowList.json`
- Add `["@salesforce/lwc-dev-server"]`
- Run `sf plugins install @salesforce/lwc-dev-server`
- Verify message and install
- `The plugin [@salesforce/lwc-dev-server] is not digitally signed but it is allow-listed.`
[@W-14129526@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-14129526)
> fix: support 403 allowlist

- .github/workflows/update-npm-version.yml
- package.json
- yarn.lock
Both @salesforce/plugin-trust and @oclif/plugin-plugins require npm. In order to ensure that we are not duplicating pinned npm versions and increasing the CLI bundle size, we get the version from plugin-plugins
This will save `17mb` in bundle size when they are out of sync
[@W-13735995@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-13735995)
> Get npm from plugin-plugins instead

- src/commands/plugins/trust/verify.ts
- src/shared/installationVerification.ts
- test/shared/installationVerification.test.ts
We suggest using `SF_NPM_REGISTRY`
> Deprecated environment variable: SFDX_NPM_REGISTRY. Please use SF_NPM_REGISTRY instead.
However, `plugin-trust` did not look for that env var when verifying signatures. 
You can link this to your locally installed `sf`. After linking and setting a bogus registry with `SF_NPM_REGISTRY`, you will see a warning
```
{
errno: -3008,
code: 'ENOTFOUND',
syscall: 'getaddrinfo',
hostname: 'registry.npmjs-foo.org'
},
```
https://github.com/forcedotcom/cli/issues/2517
[@W-14277809@](https://gus.my.salesforce.com/apex/ADM_WorkLocator?bugorworknumber=W-14277809)
> Look for SF_NPM_REGISTRY

- src/hooks/jitPluginInstall.ts
If a JIT plugin command is run with `--json` and that plugin is not yet installed (such as in a CI system) the output from the JIT install (which is not JSON) would mix with the JSON to cause problems.  This fix passes along the `--json` flag to the call to plugins:install so the output is still valid JSON.
E.g., `sf package version create ... --json` would cause output like:
```
Successfully installed @salesforce/plugin-packaging v1.27.0
{
"status": 0,
"result": {
"Id": "<PACKAGE_ID>",
...
},
"warnings": []
}
```
With the fix, the output contains only JSON.
@W-14457843@
https://github.com/forcedotcom/cli/issues/2562
> fix: pass json flag to plugins install

- src/shared/installationVerification.ts
- test/shared/installationVerification.test.ts
Allows any 403 response to proceed to plugin verification bypass. Previously restricted to errors with a more specific 403 (Forbidden) message.
forcedotcom/cli/issues/2584 
@W-14581522@
> feat: allow any 403 response to continue verification

- messages/verify.md
- src/commands/plugins/trust/verify.ts
- src/shared/installationVerification.ts
- test/nuts/plugin-install.nut.ts
- test/shared/installationVerification.test.ts
check the allowList first before making callouts via npm.  Not only should this save time for allowListed plugins, but it also means the allowList is a way of bypassing the check entirely, which is a quick-fix for the people with all the weird registry/firewall/proxy issues.
it's a broader fix than the one already merged for 
forcedotcom/cli/issues/2584
@W-14581522@
> feat: check allowList before making callouts

- package.json
- src/shared/installationVerification.ts
- src/shared/npmCommand.ts
Support semver ranges when verifying signature (e.g. `sf plugins install auth@^3.3.3`)
@W-11771849@
> fix: allow semver ranges

- messages/verify.md
- src/hooks/verifyInstallSignature.ts
- src/shared/installationVerification.ts
- test/hooks/verifyInstallSignatureHook.test.ts
- test/nuts/plugin-install.nut.ts
- Support allow-listed github urls (e.g. https://github.com/oclif/plugin-version)
- only `https://github.com/<org>/<repo>` is supported. You cannot use `https://github.com/<org>/<repo>.git`, `https://github.com/<org>/<repo>#commit`, etc...
- Display plugin name in prompt instead of `This plugin`
@W-15313997@
> feat: support allowed github urls

- package.json
- src/commands/plugins/trust/verify.ts
- src/hooks/jitPluginInstall.ts
- src/hooks/verifyInstallSignature.ts
- src/shared/NpmName.ts
- src/shared/errors.ts
- src/shared/installationVerification.ts
- test/shared/installationVerification.test.ts
- test/shared/npmName.test.ts
- yarn.lock
1. update deps to unblock devScripts automerges
1. refactor npmName to a function/interface [was not exported or used outside this library, no breaking changes] 
1. export npmName top-level (it's already a dependency of plugin-release-management and mostly duplicated here: https://github.com/salesforcecli/plugin-release-management/blob/main/src/codeSigning/NpmName.ts)
1. UT for npmName where none existed in either repo (found a bug!)
@W-15429611@
> fix: refactor npmName and export it

- package.json
- src/hooks/diagnostics.ts
- src/shared/npmCommand.ts
- yarn.lock
What does this PR do?
adds a few network checks to verify the users machine can access
yarn/npm registries
What issues does this PR fix or reference?
@W-15758164@
> feat: add network diagnostic check

- command-snapshot.json
- messages/node.info.md
- src/commands/node/info.ts
- src/shared/npmCommand.ts
- test/nuts/node-info.nut.ts
Adds a hidden `node info` command that prints the path to the bundled node/npx files.
This will be used internally only by A4D.
It re-uses the same logic already in place for plugin signature verification to resolve the path to the bundled node binary (installers) or the global one (npm installs), which users have been using for years in mac/linux/windows.
@W-18451508@
> fix: add `node info` W-18451508
